system:
  version: 3.5.0-rc
  name: Product Management System
  date: 2025-12-02
  author: Marcelo Feliciano

api:
  version: v2

# Following pattern for defining permissions: module1:action1,action2;module2:action2
auth:
  authorized: "auth:*;user:registerUser,confirm,resend-confirmation,email-change-confirmation;health:up"

security:
  cookie:
    secure: false
    path: "/"
    samesite: Lax

app:
  env: development
  domain:
  base_url: http://localhost:8080

rate_limit:
  enabled: false
  capacity: 60          # max tokens (burst) per identifier
  refill:
    tokens: 60          # tokens added each period (keep <= capacity)
    period_seconds: 60  # period length in seconds

cache:
  timeout_minutes: 120

pagination:
  page: 1
  limit: 5
  sort: id
  order: asc

homepage: "api/v1/product/list/?page=1&limit=3&sort=id&order=desc"
loginPage: "/api/v1/auth/form"
scrape_product_url: "https://web-scraping.dev/api/products?page=<page>&order=asc"

s3:
  region: us-east-1
  bucket:
    name: your-s3-bucket-name

cdn:
  domain: your-cdn-domain.com
  protocol: https
  keyPairId: your-key-pair-id