system:
  version: 3.6.0-rc
  name: Product Management System
  date: 2025-12-21
  author: Marcelo Feliciano

api:
  version: v2

# Following pattern for defining permissions: module1:action1,action2;module2:action2
auth:
  authorized: "auth:*;user:registerUser,confirm,resend-confirmation,email-change-confirmation;health:up"

security:
  cookie:
    secure: true
    path: "/"
    samesite: Lax

app:
  env: homologation
  base_url:
  domain:

rate_limit:
  enabled: false
  capacity: 60          # max tokens (burst) per identifier
  refill:
    tokens: 60          # tokens added each period (keep <= capacity)
    period_seconds: 60  # period length in seconds

pagination:
  page: 1
  limit: 5
  sort: id
  order: asc

homepage: "api/v1/product/list/?page=1&limit=3&sort=registerDate&order=desc"
loginPage: "/api/v1/auth/form"

provider:
  storage: s3
  broker: sqs

s3:
  region: us-east-1
  bucket:
    name:

sqs:
  region: us-east-1
  queue:
    name:
    url:

cdn:
  domain:
  protocol: https
  keyPairId: